# Generated by Django 4.2.26 on 2026-01-25 22:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stories", "0006_message"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Message",
        ),
    ]
