# Generated by Django 4.2.26 on 2026-01-28 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_delete_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='cover_image',
            field=models.ImageField(blank=True, default='covers/default-cover.jpg', null=True, upload_to='covers/'),
        ),
    ]
