# Generated by Django 4.2.26 on 2026-01-29 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_alter_story_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='rating',
        ),
    ]
