# Generated by Django 4.2.26 on 2026-02-04 23:35

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stories", "0009_remove_story_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to="covers/",
            ),
        ),
    ]
